image: node:10.15.3

pipelines:
  branches:
    hml:
      - step:
          name: hml uploading to heroku
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

    main:
      - step:
          name: prod uploading to heroku
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
