export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Admin } from './Admin'
export { default as ItemsProducts } from './ItemsProducts'
export { default as ForgotPassword } from './ForgotPassword'
export { default as Classificados } from './Classificados'
export { default as NotFound } from './NotFound'
export { default as Register } from './Register'
